version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio-nextjs
    ports:
      - "3000:3000" # Expose le port 3000
    restart: always # Redémarrage automatique
    environment:
      - NODE_ENV=production
    # user: "1001:1001" # Optionnel, déjà géré dans le Dockerfile 